[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Material Manager"
description="Allows you to quickly toggle between different materials"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/Vadim-Karpenko/omniverse-material-manager-extended"

# One of categories for UI.
category = "Material"

# Keywords for the extension
keywords = ["material", "materials", "manager", ]

authors = ["Vadim Karpenko"]

preview_image = "data/preview_image.jpg"

icon = "data/icons/icon.jpg"


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.stage.copypaste" = {}
"omni.kit.uiapp" = {}
"omni.kit.viewport.utility" = {  }
"omni.ui.scene" = {  }
"omni.ui" = { }
"omni.usd" = {  }
"omni.kit.usd_undo" = {}


# Main python module this extension provides, it will be publicly available as "import karpenko.materialsmanager.ext".
[[python.module]]
name = "karpenko.materialsmanager.ext"

dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]