[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Material Manager"
description="The simplest python extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Material"

# Keywords for the extension
keywords = ["material", "materials", "manager", ]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.viewport.utility" = {  }
"omni.ui.scene" = {  }
"omni.usd" = {  }

# Main python module this extension provides, it will be publicly available as "import karpenko.materialsmanager.ext".
[[python.module]]
name = "karpenko.materialsmanager.ext"

dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]